In [2]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [3]:
print(df.source.unique())

['ModernCRM' 'AnalyticsEngine' 'ModernHR' 'BillingSystem' 'ThirdPartyAPI'
 'LegacyCRM']

In [4]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

c:\Users\KIIT0001\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
import numpy as np

In [6]:
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df['log_message'].tolist())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2882.80it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [7]:
embeddings[0]

array([-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,  1.55101740e-03,
       -9.86917876e-03, -1.78956270e-01, -6.34409785e-02, -6.01761639e-02,
        2.81109158e-02,  5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
       -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,  2.71685235e-02,
       -1.49891041e-02, -3.54037657e-02, -3.62936445e-02, -1.45410765e-02,
       -5.61491773e-03,  8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
        1.00187510e-02,  1.24267349e-02, -1.39923573e-01,  7.68696293e-02,
        3.14095505e-02, -4.15247958e-03,  4.36902344e-02,  1.71250012e-02,
       -8.00951198e-02,  5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
        3.96398641e-02, -1.34371817e-01, -1.44360063e-03,  3.06704035e-03,
        1.76854044e-01,  4.44885530e-03, -1.69274509e-02,  2.24266481e-02,
       -4.35049310e-02,  6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
        1.07372422e-02, -6.04895083e-03, -7.14660808e-02, -8.45799781e-03,
       -3.18019874e-02, -1.00518376e-01,  2.25873096e-04, -1.89341009e-02,
       -3.17793973e-02,  4.00860943e-02,  2.19178163e-02, -2.59528961e-02,
        5.84525056e-02, -8.12509581e-02,  2.12029163e-02, -5.02687655e-02,
        1.32057499e-02,  1.32675481e-03,  2.27062907e-02, -3.45793478e-02,
        3.91546972e-02, -2.09433399e-02,  3.24829482e-03,  4.43961099e-02,
       -9.85357612e-02, -2.88895369e-02, -6.85023936e-03,  5.38818911e-02,
        6.46110177e-02, -2.45060585e-02,  9.21828747e-02, -7.49868751e-02,
        1.23994909e-02, -1.00026578e-01, -4.64910977e-02,  6.01570047e-02,
       -2.46480722e-02, -7.08076209e-02, -2.77270824e-02,  9.72611383e-02,
        3.85841392e-02, -1.44293057e-02, -7.46909878e-04, -1.04304878e-02,
       -1.61842871e-02,  4.43628095e-02,  9.25995968e-03,  7.14165792e-02,
        6.37917742e-02,  4.94931564e-02, -6.02567680e-02,  4.04805690e-02,
       -3.42860855e-02, -1.93881039e-02,  6.61233589e-02,  6.01589568e-02,
        1.09371776e-02, -5.38631296e-03,  1.44579662e-02,  9.25429910e-02,
       -3.14564183e-02, -1.84352025e-02,  9.91876610e-03, -1.85574219e-02,
        1.31284434e-03,  2.26702014e-05,  2.02741218e-03,  2.75256746e-02,
       -4.81928065e-02,  5.42826168e-02, -7.32066929e-02,  4.88667302e-02,
        4.98490408e-02, -9.01139528e-03, -4.68905792e-02, -4.25887071e-02,
       -8.19523931e-02,  3.87106128e-02,  7.85504058e-02,  1.46077081e-32,
        1.66706275e-02,  5.25494143e-02, -1.82448905e-02, -1.26686739e-02,
        6.52837083e-02, -2.11777352e-02, -4.06323038e-02,  4.14947495e-02,
       -2.48360801e-02, -1.33068245e-02, -5.46753556e-02, -5.99200139e-04,
       -4.89246612e-03, -6.27359450e-02, -3.84878367e-02, -6.13543652e-02,
        8.27405825e-02,  2.34379973e-02, -8.63091834e-03,  1.31003130e-02,
        6.44215122e-02, -4.41361926e-02, -6.98633417e-02, -7.36059994e-02,
       -4.33264039e-02,  6.96522417e-03, -5.05956709e-02, -1.60911996e-02,
       -5.66794015e-02,  3.35454731e-03,  5.34115247e-02,  2.47761514e-02,
       -1.47986487e-02, -2.93242969e-02,  7.30228499e-02, -1.86833944e-02,
        8.13137367e-02, -2.69967224e-02, -5.68056367e-02, -6.59389049e-02,
       -5.95394848e-03,  2.85312776e-02, -7.85358176e-02, -2.76694540e-03,
       -3.26469471e-03, -9.28332806e-02, -7.27363005e-02, -3.31903026e-02,
        1.01411112e-01,  9.79882479e-02, -9.78740230e-02,  1.98667571e-02,
        2.38837320e-02, -1.81672648e-02, -3.73708978e-02,  1.96551997e-03,
        6.34425730e-02,  1.18271559e-02, -1.12041300e-02, -3.87316644e-02,
        9.32424441e-02,  4.26628767e-03, -1.66872628e-02, -6.87464401e-02,
        1.55119859e-02, -4.97755483e-02,  3.34493034e-02,  8.00032541e-02,
        2.12282464e-02,  1.34581864e-01, -2.30729766e-02,  5.53858802e-02,
        3.07558421e-02, -2.93905940e-02,  2.31905375e-02, -9.34307799e-02,
        7.58034959e-02, -5.21208439e-03, -5.14523312e-02,  3.32688726e-02,
        3.67963351e-02, -1.06450235e-02,  1.01634776e-02, -2.07651369e-02,
       -5.85519075e-02,  4.79328595e-02,  2.13694703e-02,  8.76213461e-02,
        3.35494406e-03, -3.80336568e-02, -1.81205384e-02,  6.87449984e-03,
        5.15880026e-02, -4.75598909e-02, -6.12065606e-02, -1.45483574e-32,
        4.12801234e-03,  4.59641684e-03, -5.63900359e-02,  4.32465039e-03,
       -1.09439227e-03,  9.31954943e-03, -2.20269002e-02,  5.79564497e-02,
       -1.44787477e-02,  4.64155786e-02,  1.43542871e-01, -6.89756870e-02,
        6.09631799e-02, -8.93743932e-02,  2.40919460e-02,  2.06010658e-02,
       -2.82415487e-02, -6.48315251e-02,  5.64795695e-02, -7.48336036e-03,
       -3.52058038e-02,  8.51060525e-02,  1.30359633e-02,  2.02257764e-02,
       -1.44390641e-02, -4.63718511e-02,  1.77209619e-02,  1.59105826e-02,
       -9.51009318e-02, -3.54526863e-02,  2.08696295e-02,  3.84389190e-03,
       -8.77918154e-02,  6.44575655e-02,  1.44171156e-02,  3.84733523e-03,
        4.70991470e-02,  4.94661182e-02,  1.53862564e-02, -2.59578805e-02,
        9.10894647e-02,  1.83307882e-02, -5.89206666e-02,  2.51992680e-02,
       -3.30374353e-02,  8.23345333e-02,  1.74792372e-02,  6.48047701e-02,
       -1.19674122e-02, -3.31778415e-02,  3.00177671e-02,  3.54220010e-02,
       -1.39624272e-02,  6.69272467e-02,  3.87919769e-02,  6.06916696e-02,
        1.17958151e-03, -2.38787029e-02, -1.26930416e-01,  1.13846380e-02,
        1.59290042e-02, -1.29427500e-02, -8.63247886e-02,  8.53661261e-03,
        6.03761226e-02,  1.51121775e-02, -1.19132362e-01,  1.15234600e-02,
        5.97089604e-02, -3.93345878e-02,  1.55673325e-02,  1.04602240e-02,
       -4.72456925e-02, -2.59243399e-02,  9.98525601e-03,  3.07146404e-02,
       -7.14844763e-02,  6.98965415e-03, -1.55133577e-02,  2.18864139e-02,
       -2.78145913e-02,  6.92733005e-02, -2.75903586e-02,  2.62429845e-02,
        3.52561660e-02, -4.26419862e-02,  7.46284146e-04,  6.59866631e-02,
       -5.15105948e-02, -3.58434319e-02, -6.53440924e-03, -2.75858175e-02,
       -1.00125581e-01,  7.83326104e-02, -1.45798642e-02, -6.18457250e-08,
        2.00325698e-02,  6.59784526e-02, -2.04702560e-02,  1.64043903e-02,
        7.63001442e-02,  7.32182562e-02,  5.65784518e-03, -6.97782438e-04,
       -3.63794621e-03,  6.02393858e-02, -3.27187181e-02, -6.45838156e-02,
       -5.97952493e-02, -1.76696330e-02,  6.10143691e-03, -5.63488016e-03,
       -1.22972250e-01,  6.35818988e-02, -2.19432022e-02, -1.16406500e-01,
        2.34366246e-02, -7.23525658e-02,  2.31773835e-02, -6.55987561e-02,
       -7.42682368e-02,  2.60146223e-02,  3.59758623e-02,  7.68432692e-02,
       -3.08057331e-02, -2.34794039e-02, -6.30426034e-02, -3.62158157e-02,
       -1.03560016e-02, -4.75602485e-02, -2.87522227e-02,  2.96400599e-02,
       -5.26892208e-03,  5.67889623e-02, -3.74485948e-03,  3.09612993e-02,
        3.48226950e-02,  3.78607921e-02,  2.10155267e-02,  2.70691738e-02,
        5.25520407e-02,  7.16229230e-02, -5.53755183e-03,  4.01093923e-02,
        5.16276695e-02, -2.67314408e-02,  5.94224073e-02, -4.29224260e-02,
       -1.19760446e-02,  3.05984747e-02, -7.40331411e-02,  1.84222143e-02,
       -8.64861440e-03, -8.83557573e-02, -5.91984391e-02, -1.00920675e-04,
        1.12913631e-01,  4.57792636e-03, -4.25971746e-02,  3.22620897e-03],
      dtype=float32)

In [8]:
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

In [9]:
df['cluster'] = clusters
print(df.head())

             timestamp           source  \
0  2025-06-27 07:20:25        ModernCRM
1      1/14/2025 23:07        ModernCRM
2       1/17/2025 1:29  AnalyticsEngine
3  2025-07-12 00:24:16         ModernHR
4  2025-06-02 18:25:23    BillingSystem

                                         log_message    target_label  \
0  nova.osapi_compute.wsgi.server [req-b9718cd8-f...     HTTP Status
1     Email service experiencing issues with sending  Critical Error
2          Unauthorized access to data was attempted  Security Alert
3  nova.osapi_compute.wsgi.server [req-4895c258-b...     HTTP Status
4  nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...     HTTP Status

  complexity  cluster
0       bert        0
1       bert        1
2       bert        2
3       bert        0
4       bert        0

In [10]:
print(df.cluster.unique())

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135]

In [11]:
#size of each cluster
print(df['cluster'].value_counts())

cluster
0      1017
5       147
11      100
13       86
7        60
       ...
102       1
103       1
105       1
106       1
135       1
Name: count, Length: 136, dtype: int64

In [12]:
df[df.cluster == 1].head()

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1

In [13]:
import re

In [14]:
regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }

In [15]:
def classify_with_regex(log_message, regex_patterns = regex_patterns):
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
    return "Unclassified"

In [16]:
classify_with_regex("User User123 logged OUT.")

'User Action'

In [17]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [18]:
#print any 5 rows which are not unclassified
print(df[df['regex_label'] != "Unclassified"].head())

          timestamp         source  \
7   10/11/2025 8:44       ModernHR
14    1/4/2025 1:43  ThirdPartyAPI
15    5/1/2025 9:41      ModernCRM
18  2/22/2025 17:49      ModernCRM
27  9/24/2025 19:57  ThirdPartyAPI

                                          log_message         target_label  \
7   File data_6169.csv uploaded successfully by us...  System Notification
14  File data_3847.csv uploaded successfully by us...  System Notification
15                     Backup completed successfully.  System Notification
18           Account with ID 5351 created by User634.          User Action
27                           User User685 logged out.          User Action

   complexity  cluster          regex_label
7       regex        4  System Notification
14      regex        4  System Notification
15      regex        8  System Notification
18      regex        9          User Action
27      regex       11          User Action

In [19]:
#print the distribution of regex labels
print(df['regex_label'].value_counts())

regex_label
Unclassified           1910
System Notification     356
User Action             144
Name: count, dtype: int64

In [20]:
df_non_regex = df[df['regex_label'] == "Unclassified"].copy()
df_non_regex.shape

(1910, 7)

In [21]:
#find rare labels in target_label column
rare_labels = df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() < 10]
print(rare_labels)

target_label
Workflow Error         4
Deprecation Warning    3
Name: count, dtype: int64

In [22]:
#find those 'source' whose target_label is in rare_labels
rare_sources = df_non_regex[df_non_regex['target_label'].isin(rare_labels.index)]['source'].unique()
print(rare_sources)

['LegacyCRM']

In [26]:
df_non_rare = df_non_regex[df_non_regex.source != rare_sources[0]]
df_non_rare.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [25]:
#Apply BERT for all sources except those in rare_sources

In [31]:
filtered_embeddings = model.encode(df_non_rare['log_message'].tolist())
filtered_embeddings[0]

array([-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,  1.55101740e-03,
       -9.86917876e-03, -1.78956270e-01, -6.34409785e-02, -6.01761639e-02,
        2.81109158e-02,  5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
       -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,  2.71685235e-02,
       -1.49891041e-02, -3.54037657e-02, -3.62936445e-02, -1.45410765e-02,
       -5.61491773e-03,  8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
        1.00187510e-02,  1.24267349e-02, -1.39923573e-01,  7.68696293e-02,
        3.14095505e-02, -4.15247958e-03,  4.36902344e-02,  1.71250012e-02,
       -8.00951198e-02,  5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
        3.96398641e-02, -1.34371817e-01, -1.44360063e-03,  3.06704035e-03,
        1.76854044e-01,  4.44885530e-03, -1.69274509e-02,  2.24266481e-02,
       -4.35049310e-02,  6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
        1.07372422e-02, -6.04895083e-03, -7.14660808e-02, -8.45799781e-03,
       -3.18019874e-02, -1.00518376e-01,  2.25873096e-04, -1.89341009e-02,
       -3.17793973e-02,  4.00860943e-02,  2.19178163e-02, -2.59528961e-02,
        5.84525056e-02, -8.12509581e-02,  2.12029163e-02, -5.02687655e-02,
        1.32057499e-02,  1.32675481e-03,  2.27062907e-02, -3.45793478e-02,
        3.91546972e-02, -2.09433399e-02,  3.24829482e-03,  4.43961099e-02,
       -9.85357612e-02, -2.88895369e-02, -6.85023936e-03,  5.38818911e-02,
        6.46110177e-02, -2.45060585e-02,  9.21828747e-02, -7.49868751e-02,
        1.23994909e-02, -1.00026578e-01, -4.64910977e-02,  6.01570047e-02,
       -2.46480722e-02, -7.08076209e-02, -2.77270824e-02,  9.72611383e-02,
        3.85841392e-02, -1.44293057e-02, -7.46909878e-04, -1.04304878e-02,
       -1.61842871e-02,  4.43628095e-02,  9.25995968e-03,  7.14165792e-02,
        6.37917742e-02,  4.94931564e-02, -6.02567680e-02,  4.04805690e-02,
       -3.42860855e-02, -1.93881039e-02,  6.61233589e-02,  6.01589568e-02,
        1.09371776e-02, -5.38631296e-03,  1.44579662e-02,  9.25429910e-02,
       -3.14564183e-02, -1.84352025e-02,  9.91876610e-03, -1.85574219e-02,
        1.31284434e-03,  2.26702014e-05,  2.02741218e-03,  2.75256746e-02,
       -4.81928065e-02,  5.42826168e-02, -7.32066929e-02,  4.88667302e-02,
        4.98490408e-02, -9.01139528e-03, -4.68905792e-02, -4.25887071e-02,
       -8.19523931e-02,  3.87106128e-02,  7.85504058e-02,  1.46077081e-32,
        1.66706275e-02,  5.25494143e-02, -1.82448905e-02, -1.26686739e-02,
        6.52837083e-02, -2.11777352e-02, -4.06323038e-02,  4.14947495e-02,
       -2.48360801e-02, -1.33068245e-02, -5.46753556e-02, -5.99200139e-04,
       -4.89246612e-03, -6.27359450e-02, -3.84878367e-02, -6.13543652e-02,
        8.27405825e-02,  2.34379973e-02, -8.63091834e-03,  1.31003130e-02,
        6.44215122e-02, -4.41361926e-02, -6.98633417e-02, -7.36059994e-02,
       -4.33264039e-02,  6.96522417e-03, -5.05956709e-02, -1.60911996e-02,
       -5.66794015e-02,  3.35454731e-03,  5.34115247e-02,  2.47761514e-02,
       -1.47986487e-02, -2.93242969e-02,  7.30228499e-02, -1.86833944e-02,
        8.13137367e-02, -2.69967224e-02, -5.68056367e-02, -6.59389049e-02,
       -5.95394848e-03,  2.85312776e-02, -7.85358176e-02, -2.76694540e-03,
       -3.26469471e-03, -9.28332806e-02, -7.27363005e-02, -3.31903026e-02,
        1.01411112e-01,  9.79882479e-02, -9.78740230e-02,  1.98667571e-02,
        2.38837320e-02, -1.81672648e-02, -3.73708978e-02,  1.96551997e-03,
        6.34425730e-02,  1.18271559e-02, -1.12041300e-02, -3.87316644e-02,
        9.32424441e-02,  4.26628767e-03, -1.66872628e-02, -6.87464401e-02,
        1.55119859e-02, -4.97755483e-02,  3.34493034e-02,  8.00032541e-02,
        2.12282464e-02,  1.34581864e-01, -2.30729766e-02,  5.53858802e-02,
        3.07558421e-02, -2.93905940e-02,  2.31905375e-02, -9.34307799e-02,
        7.58034959e-02, -5.21208439e-03, -5.14523312e-02,  3.32688726e-02,
        3.67963351e-02, -1.06450235e-02,  1.01634776e-02, -2.07651369e-02,
       -5.85519075e-02,  4.79328595e-02,  2.13694703e-02,  8.76213461e-02,
        3.35494406e-03, -3.80336568e-02, -1.81205384e-02,  6.87449984e-03,
        5.15880026e-02, -4.75598909e-02, -6.12065606e-02, -1.45483574e-32,
        4.12801234e-03,  4.59641684e-03, -5.63900359e-02,  4.32465039e-03,
       -1.09439227e-03,  9.31954943e-03, -2.20269002e-02,  5.79564497e-02,
       -1.44787477e-02,  4.64155786e-02,  1.43542871e-01, -6.89756870e-02,
        6.09631799e-02, -8.93743932e-02,  2.40919460e-02,  2.06010658e-02,
       -2.82415487e-02, -6.48315251e-02,  5.64795695e-02, -7.48336036e-03,
       -3.52058038e-02,  8.51060525e-02,  1.30359633e-02,  2.02257764e-02,
       -1.44390641e-02, -4.63718511e-02,  1.77209619e-02,  1.59105826e-02,
       -9.51009318e-02, -3.54526863e-02,  2.08696295e-02,  3.84389190e-03,
       -8.77918154e-02,  6.44575655e-02,  1.44171156e-02,  3.84733523e-03,
        4.70991470e-02,  4.94661182e-02,  1.53862564e-02, -2.59578805e-02,
        9.10894647e-02,  1.83307882e-02, -5.89206666e-02,  2.51992680e-02,
       -3.30374353e-02,  8.23345333e-02,  1.74792372e-02,  6.48047701e-02,
       -1.19674122e-02, -3.31778415e-02,  3.00177671e-02,  3.54220010e-02,
       -1.39624272e-02,  6.69272467e-02,  3.87919769e-02,  6.06916696e-02,
        1.17958151e-03, -2.38787029e-02, -1.26930416e-01,  1.13846380e-02,
        1.59290042e-02, -1.29427500e-02, -8.63247886e-02,  8.53661261e-03,
        6.03761226e-02,  1.51121775e-02, -1.19132362e-01,  1.15234600e-02,
        5.97089604e-02, -3.93345878e-02,  1.55673325e-02,  1.04602240e-02,
       -4.72456925e-02, -2.59243399e-02,  9.98525601e-03,  3.07146404e-02,
       -7.14844763e-02,  6.98965415e-03, -1.55133577e-02,  2.18864139e-02,
       -2.78145913e-02,  6.92733005e-02, -2.75903586e-02,  2.62429845e-02,
        3.52561660e-02, -4.26419862e-02,  7.46284146e-04,  6.59866631e-02,
       -5.15105948e-02, -3.58434319e-02, -6.53440924e-03, -2.75858175e-02,
       -1.00125581e-01,  7.83326104e-02, -1.45798642e-02, -6.18457250e-08,
        2.00325698e-02,  6.59784526e-02, -2.04702560e-02,  1.64043903e-02,
        7.63001442e-02,  7.32182562e-02,  5.65784518e-03, -6.97782438e-04,
       -3.63794621e-03,  6.02393858e-02, -3.27187181e-02, -6.45838156e-02,
       -5.97952493e-02, -1.76696330e-02,  6.10143691e-03, -5.63488016e-03,
       -1.22972250e-01,  6.35818988e-02, -2.19432022e-02, -1.16406500e-01,
        2.34366246e-02, -7.23525658e-02,  2.31773835e-02, -6.55987561e-02,
       -7.42682368e-02,  2.60146223e-02,  3.59758623e-02,  7.68432692e-02,
       -3.08057331e-02, -2.34794039e-02, -6.30426034e-02, -3.62158157e-02,
       -1.03560016e-02, -4.75602485e-02, -2.87522227e-02,  2.96400599e-02,
       -5.26892208e-03,  5.67889623e-02, -3.74485948e-03,  3.09612993e-02,
        3.48226950e-02,  3.78607921e-02,  2.10155267e-02,  2.70691738e-02,
        5.25520407e-02,  7.16229230e-02, -5.53755183e-03,  4.01093923e-02,
        5.16276695e-02, -2.67314408e-02,  5.94224073e-02, -4.29224260e-02,
       -1.19760446e-02,  3.05984747e-02, -7.40331411e-02,  1.84222143e-02,
       -8.64861440e-03, -8.83557573e-02, -5.91984391e-02, -1.00920675e-04,
        1.12913631e-01,  4.57792636e-03, -4.25971746e-02,  3.22620897e-03],
      dtype=float32)

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [38]:
X_train, X_test, y_train, y_test = train_test_split(filtered_embeddings, df_non_rare['target_label'], test_size=0.3, random_state=42)

In [39]:
clf = LogisticRegression(max_iter=1000)

In [40]:
clf.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [41]:
y_pred = clf.predict(X_test)

In [42]:
report = classification_report(y_test, y_pred)

In [43]:
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [44]:
import joblib

In [ ]:
joblib.dump(clf, '../models/log_classifier_model.joblib')

['models/log_classifier_model.joblib']